# Generated by Django 4.2.25 on 2025-10-13 17:30

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilestudent',
            options={'verbose_name': 'Профиль студента', 'verbose_name_plural': 'Профили студентов'},
        ),
        migrations.AlterModelOptions(
            name='profileteacher',
            options={'verbose_name': 'Профиль преподавателя', 'verbose_name_plural': 'Профили преподавателей'},
        ),
        migrations.AddField(
            model_name='profilestudent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profilestudent',
            name='github',
            field=models.URLField(blank=True, verbose_name='GitHub'),
        ),
        migrations.AddField(
            model_name='profilestudent',
            name='group',
            field=models.CharField(blank=True, max_length=50, verbose_name='Группа'),
        ),
        migrations.AddField(
            model_name='profilestudent',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='profilestudent',
            name='portfolio',
            field=models.URLField(blank=True, verbose_name='Портфолио'),
        ),
        migrations.AddField(
            model_name='profilestudent',
            name='telegram',
            field=models.CharField(blank=True, max_length=100, verbose_name='Telegram'),
        ),
        migrations.AddField(
            model_name='profilestudent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='profileteacher',
            name='academic_degree',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ученая степень'),
        ),
        migrations.AddField(
            model_name='profileteacher',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 10, 13, 17, 30, 29, 603783, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profileteacher',
            name='expertise',
            field=models.TextField(blank=True, help_text='Ваши основные направления исследований и экспертизы', verbose_name='Области экспертизы'),
        ),
        migrations.AddField(
            model_name='profileteacher',
            name='office',
            field=models.CharField(blank=True, max_length=100, verbose_name='Кабинет'),
        ),
        migrations.AddField(
            model_name='profileteacher',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='profileteacher',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='profilestudent',
            name='bio',
            field=models.TextField(blank=True, help_text='Расскажите о своих интересах, достижениях, опыте', verbose_name='О себе'),
        ),
        migrations.AlterField(
            model_name='profilestudent',
            name='course',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 курс'), (2, '2 курс'), (3, '3 курс'), (4, '4 курс'), (5, '5 курс'), (6, '6 курс')], null=True, verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='profilestudent',
            name='institute',
            field=models.CharField(blank=True, max_length=255, verbose_name='Институт/Факультет'),
        ),
        migrations.AlterField(
            model_name='profilestudent',
            name='skills',
            field=models.TextField(blank=True, help_text='Перечислите ваши навыки через запятую (Python, JavaScript, UI/UX Design, etc.)', verbose_name='Навыки и компетенции'),
        ),
        migrations.AlterField(
            model_name='profileteacher',
            name='bio',
            field=models.TextField(blank=True, help_text='Научные интересы, публикации, достижения', verbose_name='Биография'),
        ),
    ]
