# Generated by Django 4.2.25 on 2025-10-13 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profilestudent_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilestudent',
            options={},
        ),
        migrations.AlterModelOptions(
            name='profileteacher',
            options={},
        ),
        migrations.RemoveField(
            model_name='profilestudent',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='profilestudent',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='profileteacher',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='profileteacher',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='profilestudent',
            name='bio',
            field=models.TextField(blank=True, verbose_name='О себе'),
        ),
        migrations.AlterField(
            model_name='profilestudent',
            name='skills',
            field=models.TextField(blank=True, help_text='Перечислите ваши навыки через запятую', verbose_name='Навыки и компетенции'),
        ),
        migrations.AlterField(
            model_name='profileteacher',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Биография'),
        ),
        migrations.AlterField(
            model_name='profileteacher',
            name='expertise',
            field=models.TextField(blank=True, verbose_name='Области экспертизы'),
        ),
    ]
