# Generated by Django 4.2.25 on 2025-10-13 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_fix_course_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilestudent',
            name='skills',
            field=models.TextField(blank=True, verbose_name='Навыки и компетенции'),
        ),
    ]
